### ISSUE TITLE
Running out of memory with preg_replace()

### ISSUE THREAD

**Issue by elvismdev** [troydavisson/PHRETS#37] opened 2014-03-02 07:33 UTC
After around a couple of hours importing listings into wp database it gets out of memory always by the same lines 246 and 248 with a preg_replace()

Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 2178151 bytes) in /home/www/public_html/custom-scripts/phrets/phrets.php on line 246

**Comment by ty2u** [comment] 2015-04-20 08:01
Hey there,

Is this still an issue in the latest v2 release? Because I am trying to sync 35k records and it seems like it has a memory leak but I'm not sure if this is the cause or if it's something else. I tried the for loop code you added but it doesn't fix it. I also tried setting several variables to null after they are no longer used but that didn't help. Especially with pictures I noticed it.

If it doesn't still have a memory leak issue then it might be something else in my setup. Just curious if anyone was aware if it still exists and if there are any fixes or do I have to implement workarounds?

Thanks!

**Comment by troydavisson** [comment] 2015-04-22 01:16
This is likely still an issue, yes.  My earlier tests with my hack solution didn't produce results worth pursuing any further.

**Comment by ty2u** [comment] 2015-04-22 01:34
Thank you for the response!

In my setup it appears it will leak about 10 gigs of RAM to sync those 35k listings, though I have yet to actually complete a full sync due to various issues like first running out of memory, then not being able to connect to CREA any longer and Guzzle gave a 503 error code. But I shall figure it out eventually with memory leak or not.

Thank you for all your hard work!

**Comment by troydavisson** [comment] 2017-03-19 19:27
The `2.3` dev branch contains some changes which should help with this.  For those using 2.x, if you could try and version and report back with your findings on memory usage, I'd appreciate it.

**Comment by troydavisson** [comment] 2017-04-01 04:35
2.3 was released this evening.  For those having memory issues using 2.x, I'd recommend upgrading to this latest version for memory improvements.  No other changes are planned for the old 1.x version, so I'll go ahead and close this issue.

**Closed by troydavisson** 2017-04-01 04:35 UTC
Labels: 1.x, 2.x, memory, needs verified

**Comment by CrestApps** [comment] 2019-01-08 23:56
I am getting a Out of memory allocation from `preg_replace` function

Line 38 of `troydavisson\phrets\src\Parsers\GetObject\Multiple.php` file

It happens when I try to download lots of images from using GetObject() method.

I tried downloading all images for 50 properties at the same time.

![screenshot_1](https://user-images.githubusercontent.com/24724371/50866170-bde07180-135d-11e9-9e98-c78116dbda3f.png)

**Comment by naapak** [comment] 2019-04-11 14:30
Is there a solution or work around to this problem?
